### ISSUE TITLE
JSON format error for some IPs

### ISSUE THREAD

**Issue by daga480** [mikebanks/AbuseIPdbSCAN#1]
I provided a list of IPs and the script works great for the most part but for some IPs it just returns a "JSON format error" (one line for each IP skipped, some times 20+ in a row but continues fine after that). 

Not sure if it's something on AbuseIPDB's end so just submitting in case someone was aware of the issue or a workaround.

**Comment by mikebanks** [comment]
Thanks for the report. Can you provide me with some of the IPs that are causing the error?

**Comment by daga480** [comment]
Here you go - about 50 were removed from the error list after running again today - but still about 300 remaining.
[JSON_Error.txt](https://github.com/mikebanks/AbuseIPdbSCAN/files/1505071/JSON_Error.txt)

**Comment by mikebanks** [comment]
Thanks @daga480 for the example IP. I have pushed a fix: https://github.com/mikebanks/AbuseIPdbSCAN/commit/c302ab46076bd8f827409244255c29e7b463fe7b

**Comment by mikebanks** [comment]
Hmm. I'll take another look.

**Comment by mikebanks** [comment]
OK sorry for the delay, this one was an interesting one. The code works, but apparently, some of the IPs are sending back categories numbers from the API that is not in their documentation. I put in a default category that will take into account weird categories that the API spits out. I have now pushed another fix: https://github.com/mikebanks/AbuseIPdbSCAN/commit/54c11682952b430921bb73dc2f5c23e51665b0d8

**Comment by mikebanks** [comment]
I've reached out to them to get clarification on these unknown categories. If you could send me all of the IPs that come back with unknown and I'll update that tool once they clarify what the categories are.

**Comment by daga480** [comment]
Thanks Mike!  Below are the unknown category IPs:

123.125.67.221
123.125.71.77
177.201.66.18
179.212.199.137
180.76.15.138
182.137.14.229
185.73.168.159
190.90.44.46
190.248.68.178
200.29.140.53

**Comment by mikebanks** [comment]
Ok, thanks... Great news. By brute forcing (using the web_gui on their site using the IPs you provided) I was able to decipher what the categories are. Pushing the update now: https://github.com/mikebanks/AbuseIPdbSCAN/commit/51c8af6b70bf515289f0a225c47b155beda0bccf

**Comment by daga480** [comment]
FYI: some more Unknown categories:

37.157.2.239
69.172.216.111
69.172.216.55
69.172.216.58
72.21.81.200
72.21.91.29
104.18.25.243
204.79.197.200
204.79.197.229

**Comment by mikebanks** [comment]
@daga480 all worked for me. You may want to make sure you are on the latest version. I updated a while ago. Ensure you have categories 3-23.
