### ISSUE TITLE
IP returning abuse reports via web but not API

### ISSUE THREAD

**Issue by daga480** [mikebanks/AbuseIPdbSCAN#2]
218.4.177.21 shows as reported 118 times online but when running through the script it says: 

218.4.177.21:  No Abuse Reports

10 other IPs run at same time reported correctly. Using latest script but w/ Python 2.7.15

**Comment by mikebanks** [comment]
Hi @daga480, per the API documentation, the default parameters of API requests only go back 30 days. (https://www.abuseipdb.com/api.html)

There could be a discussion on stale-ness of IP information and accuracy, but this is definitely not the forum for this. This is why I left the API request to the default values. 

The workaround here to get the results you are looking will be to manually edit the request in the script and include the days' options to go back further than 30 days. More information on how that should look is also in the link mentioned above.

Actions:

- [ ] I may look into adding a switch to change this in the future for the user to create a better experience.
- [ ] I will also take the action to include this information in the readme.

**Comment by mikebanks** [comment]
Solved by ba1af3d3c8228eb71ed77d6caef27cd6e0120f4f
