### ISSUE TITLE
Bug with API 2.0 and CSV export

### ISSUE THREAD

**Issue by elbauldelgeek** [mikebanks/AbuseIPdbSCAN#4]
Hello,

I detected a bug in this tool using a AbuseIPDB API 2.0

if I execute the following command I get the following error and the output file is empty

this error only happens if the IP file contains more than 5 consecutive ips

/usr/bin/python3 /AbuseIPDB.py -f list-ips.txt -c export.csv

Traceback (most recent call last):
  File "/AbuseIPDB.py", line 283, in <module>
    main()
  File "/AbuseIPDB.py", line 268, in main
    check_file(args.file, days)
  File "/AbuseIPDB.py", line 171, in check_file
    check_ip(file_item, days)
  File "/AbuseIPDB.py", line 157, in check_ip
    get_report(logs)
  File "/AbuseIPDB.py", line 223, in get_report
    keys = logs[0].keys()
IndexError: list index out of range

Please , Can you check it out?

**Comment by mikebanks** [comment]
Did you include your APIkey in the script before you ran it?

**Comment by mikebanks** [comment]
@elbauldelgeek Figured this out and fixed in https://github.com/mikebanks/AbuseIPdbSCAN/commit/0cc4681e41fa3d6f25384072ad3e8de0e45b080e
