### ISSUE TITLE
With CSV export, the content of a column is different in each line.

### ISSUE THREAD

**Issue by elbauldelgeek** [mikebanks/AbuseIPdbSCAN#6]
Hello,

I have detected using this script and the API V2 that with the CSV export, the content that is exported is not consistent on every line so the CSV exported is not very helpful.
[text-export.txt](https://github.com/mikebanks/AbuseIPdbSCAN/files/3721648/text-export.txt)

example of inconsistent CSV content.

BR - 1H : (318)  
 Protection Against DDoS WordPress plugin :  
 ""odzyskiwanie danych help-dysk"" 
 IP Address Ranges by Country : BR 
 NAME ASN : ASN264496 
 
 IP : 131.255.225.238 
 
 CIDR : 131.255.225.0/24 
 
 PREFIX COUNT : 8 
 
 UNIQUE IP COUNT : 2048 
 
 
 WYKRYTE ATAKI Z ASN264496 :  
  1H - 1 
  3H - 1 
  6H - 1 
 12H - 1 
 24H - 1 

Can you check it out? I think it's a bug.

**Comment by mikebanks** [comment]
@elbauldelgeek :  Took a while to get around to this, but I think I have a fix for you, can you check out the beta branch and see if this commit (https://github.com/mikebanks/AbuseIPdbSCAN/commit/6a810a838d8656c804374af42780a9a626b685ef) fixes your issue? 

If it does I'll move it to master.

**Comment by elbauldelgeek** [comment]
Hello,

I tested with the new version but the problem continue .

"reportedAt","comment","categories","reporterId","reporterCountryCode","reporterCountryName","ipAddress","isp","domain","usageType","countryName","isWhitelisted","abuseConfidenceScore","to>
"2019-10-11T16:00:25+01:00","Port scan: Attack repeated for 24 hours","[14, 15, 20]","14969","DE","Germany","131.255.225.238","IR Tecnologia Ltda ME","fibralink.net.br","Fixed Line ISP","B>
"2019-10-07T00:08:18+01:00","88/tcp 82/tcp 1588/tcp...
[2019-09-26/10-06]4pkt,3pt.(tcp)","[14]","20262","JP","Japan","131.255.225.238","IR Tecnologia Ltda ME","fibralink.net.br","Fixed Line ISP","Brazil","False","35","6"
"2019-10-04T21:19:33+01:00","82/tcp 1588/tcp
[2019-09-26/10-04]2pkt","[14]","20262","JP","Japan","131.255.225.238","IR Tecnologia Ltda ME","fibralink.net.br","Fixed Line ISP","Brazil","False","35","6"
"2019-09-29T02:38:37+01:00",""" ""","[14]","28404","RU","Russian Federation","131.255.225.238","IR Tecnologia Ltda ME","fibralink.net.br","Fixed Line ISP","Brazil","False","35","6"
"2019-09-26T11:18:27+01:00","1588/tcp
[2019-09-26]1pkt","[14]","20262","JP","Japan","131.255.225.238","IR Tecnologia Ltda ME","fibralink.net.br","Fixed Line ISP","Brazil","False","35","6"
"2019-09-22T06:39:12+01:00","IP Ban Report : https://help-dysk.pl/wordpress-firewall-plugins/ip/131.255.225.238/
 BR - 1H : (318)
 Protection Against DDoS WordPress plugin :
 ""odzyskiwanie danych help-dysk""
 IP Address Ranges by Country : BR
 NAME ASN : ASN264496

 IP : 131.255.225.238

 CIDR : 131.255.225.0/24

 PREFIX COUNT : 8

 UNIQUE IP COUNT : 2048


 WYKRYTE ATAKI Z ASN264496 :
  1H - 1
  3H - 1
  6H - 1
 12H - 1
 24H - 1

 INFO : SERVER - ABB - Looking for resource vulnerabilities Detected and Blocked by ADMIN  - data recovery","[4, 6, 14, 15, 18, 20, 21]","25212","FR","France","131.255.225.238","IR Tecnolo>
"2019-10-13T10:21:31+01:00","[portscan] tcp/81 [alter-web/web-proxy]
*(RWIN=65535)(10131147)","[14, 21]","13354","RU","Russian Federation","159.203.197.9","DigitalOcean LLC","digitalocean.com","Data Center/Web Hosting/Transit","United States","False","100",>
"2019-10-13T04:35:12+01:00","Honeypot hit, critical abuseConfidenceScore, incoming Traffic from this IP","[18]","24608","DE","Germany","159.203.197.9","DigitalOcean LLC","digitalocean.com">
"2019-10-11T02:11:45+01:00","2019-10-11 03:02:01 SMTP protocol synchronization error (input sent whostnamehout wahostnameing for greeting): rejected connection from H=[159.203.197.9] input>
2019-10-11 03:02:01 SMTP protocol synchronization error (input sent whostnamehout wahostnameing for greeting): rejected connection from H=[159.203.197.9] input=""EHLO zg-0911a-59rn""
2019-10-11 03:02:16 SMTP protocol synchronization error (input sent whostnamehout wahostnameing for greeting): rejected connection from H=[159.203.197.9] input=""EHLO zg-0911a-59rn""


........
-----------------------------------------------

**Comment by mikebanks** [comment]
Can I have the command you are using as well as the file? I am not getting
the same output as you.

**Comment by mikebanks** [comment]
Tried a more elegant implementation that should solve you issue: 3c840cb <- See if that one works for you.

**Comment by elbauldelgeek** [comment]
Hey, guys,

I have tested the new version of the script and now the behavior is as follows.

When the result you are going to get is incoherent directly the answer is empty

Exemple: 

root@test:/# python3 AbuseIPDB.py -i 131.255.225.238
root@test:/#

https://www.abuseipdb.com/check/131.255.225.238

**Comment by mikebanks** [comment]
It took me a while to get. some time to work on this, but fixed this issue and did some overall script improvement as well. Can you verify you don't run into any more issues here for this one: https://github.com/mikebanks/AbuseIPdbSCAN/pull/7/commits/432f129736a039845667633eb54885cf20174b45 ?

**Comment by elbauldelgeek** [comment]
Hello,

I tried it with this new script and the problem continues.

If I try to select a column from the extracted CSV, the data is not consistent.

awk -F, '$1' file.csv

**Comment by mikebanks** [comment]
Which IP produces this now?

**Comment by elbauldelgeek** [comment]
Hello,

i attach the list
[ips-problem.txt](https://github.com/mikebanks/AbuseIPdbSCAN/files/4427229/ips-problem.txt)

**Comment by mikebanks** [comment]
So I ran against this whole list. I am pretty sure it's breaking now in this case because of the ability for people to have a freeform field, and it's probably breaking the delimiting. JSON "-j" or JSONL "-l" both works. The only way I can imagine to fix this would be to remove CSV and TSV altogether or manually remove bad characters. When you get in the business or changing data, it's not ideal.

I'll have to think about what I will do. If you have any ideas please let me know.

**Comment by elbauldelgeek** [comment]
Hello,

I can imagine how difficult this is,

One option I can think of is to create an empty csv table with the titles of each row, then launch the api scan and fit the data in the corresponding row, in case a row of information is empty, it would be replaced by a 0.

Another option would be to make a selective CSV, which allows you to say that you want to import into the CSV. I only need to know the score and the IP. The other information is not used.

**Comment by mikebanks** [comment]
I think I will just make recommended output options for JSON and JSONL. I will make a disclaimer about the CSV/TSV. JSON is truly the industry standard. CSV/TSV will work in most cases, but given it's a free form field, it will always be susceptible to being parsed incorrectly.

Customizing the output field of the results might be something I support in the future.
